Home2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('esp_wifi.urls'))
]

esp_wifi/urls.py
from django.urls import path
from . import views

app_name = 'esp_wifi'

urlpatterns = [
    path('', views.index, name='index'),
    path('esp<int:pk>/', views.esp_view, name='esp'),
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('read<int:pk>/', views.read, name='read'),
    path('select_command<int:pk>/', views.select_command, name="select_command"),
    path('signup/', views.signup, name="signup"),
]

esp_wifi/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Esp(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activated = models.IntegerField(blank=True, default=0)


class Command(models.Model):
    name = models.CharField(max_length=100)
    esp = models.ForeignKey(Esp, on_delete=models.CASCADE)

esp_wifi/forms.py
from django.forms import ModelForm, CharField, PasswordInput, TextInput, Form
from .models import Esp, Command
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User


class Esp_form(ModelForm):
    name = CharField(widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Esp
        fields = ['name']
        labels = {
            'name': _('Chip name')
        }


class Command_form(ModelForm):
    name = CharField(widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Command
        fields = ['name']
        labels = {
            'name': _('Command')
        }


class Login_form(ModelForm):
    password = CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    username = CharField(widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class Signup_form(Form):
    username = CharField(widget=TextInput(attrs={'class': 'form-control'}))
    password1 = CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(widget=PasswordInput(attrs={'class': 'form-control'}))

esp_wifi/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .forms import Esp_form, Command_form, Login_form
from django.contrib.auth import login, logout, authenticate
from .models import Esp, Command
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def index(request):
    context = {}
    if request.user.is_active:
        context['form'] = Esp_form(None)
        if request.method == "POST":
            form = Esp_form(request.POST)
            if form.is_valid():
                esp = form.save(commit=False)
                esp.user = request.user
                esp.save()
            else:
                context['form'] = form
        context['esps'] = request.user.esp_set.all()
    return render(request, 'esp_wifi/index.html', context)


def esp_view(request, pk):
    esp = Esp.objects.get(pk=pk)
    if request.user.is_active and esp.user == request.user:
        context = {'esp': esp}
        form = Command_form(None)
        if request.method == "POST":
            form = Command_form(request.POST)
            if form.is_valid():
                command = form.save(commit=False)
                command.esp = esp
                command.save()
                esp.activated = command.pk
                esp.save()
                form = Command_form(None)
        context['form'] = form
        context['commands'] = request.user.esp_set.get(pk=pk).command_set.all()[::-1]
        if Esp.objects.get(pk=pk).activated:
            context['the_command'] = Command.objects.get(pk=Esp.objects.get(pk=pk).activated)
        return render(request, 'esp_wifi/esp.html', context)
    else:
        return HttpResponseRedirect("https://www.pornhub.com/")


def sign_in(request):
    context = {}
    form = Login_form(None)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('esp_wifi:index')
    context['form'] = form
    return render(request, 'esp_wifi/login.html', context)


def sign_out(request):
    logout(request)
    return redirect('esp_wifi:index')


def read(request, pk):
    context = {}
    esp_object = Esp.objects.get(pk=pk)
    if esp_object.activated:
        reading = Command.objects.get(pk=esp_object.activated).name
    else:
        reading = esp_object.command_set.all()[::-1][0].name
    context['reading'] = reading
    return render(request, 'esp_wifi/read.html', context)


def select_command(request, pk):
    esp = Esp.objects.get(pk=Command.objects.get(pk=pk).esp.pk)
    esp.activated = pk
    esp.save()
    return redirect('esp_wifi:esp', Command.objects.get(pk=pk).esp.pk)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('esp_wifi:index')
    else:
        form = UserCreationForm()
    return render(request, 'esp_wifi/sign_up.html', {'form': form})

esp_wifi/templates/esp_wifi/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'esp_wifi:index' %}">Offcanvas navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    {% if not request.user.is_active %}
                        <a class="nav-link" href="{% url 'esp_wifi:login' %}">Log in</a>
                        <a class="nav-link" href="{% url 'esp_wifi:signup' %}">Sign up</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'esp_wifi:logout' %}">Log out</a>
                    {% endif %}
                  </li>
                    <!-- Item dropdown!
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  -->
                </ul>
                  <!-- SEARCH BAR
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                -->
              </div>
            </div>
          </div>
        </nav>
    </header>
    <div class="p-4">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

esp_wifi/templates/esp_wifi/esp.html
{% extends 'esp_wifi/base.html' %}
{% block body %}
    <h3>{{ esp.name }}: {{ esp.pk }}</h3>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
        <div class="py-3">
            <button class="btn btn-success" type="submit" value="Submit!">Submit!</button>
        </div>
    </form>
    {% if commands %}
        <ul class="list-group">
        {% for command in commands %}
            {% if command == the_command %}
                <li class="list-group-item list-group-item-action active">{{ command.name }}</li>
            {% else %}
                <a href="{% url 'esp_wifi:select_command' command.pk %}" class="list-group-item list-group-item-action">{{ command.name }}</a>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

esp_wifi/templates/esp_wifi/index.html
{% extends 'esp_wifi/base.html' %}
{% block body %}
    {% if request.user.is_active %}
        <h1>{{ request.user.username }}</h1>
        {% if form %}
            <form action="" method="post">{% csrf_token %}
                {{ form }}
                <div class="py-3">
                    <button class="btn btn-success" type="submit" value="Submit!">Submit!</button>
                </div>
            </form>
        {% endif %}
        {% if esps %}
            <h4 class="pt-4">ESP's:</h4>
            <ul class="list-group">
                {% for esp in esps %}
                    <a style="font-size: 110%" class="list-group-item list-group-item-action" href="{% url 'esp_wifi:esp' esp.pk %}">{{ esp.name }}</a>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
{% endblock %}

esp_wifi/templates/esp_wifi/login.html
{% extends 'esp_wifi/base.html' %}
{% block body %}
    <form action="" method="post">{% csrf_token %}
        {{ form }}
        <div class="p-3">
            <button class="btn btn-success" type="submit" value="Submit!">Submit!</button>
        </div>
    </form>
{% endblock %}

esp_wifi/templates/esp_wifi/read.html
{{ reading }}

esp_wifi/templates/esp_wifi/sign_up.html
{% extends 'esp_wifi/base.html' %}
{% block body %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up!</button>
  </form>
{% endblock %}